export interface TagRule {
  tag: string
  subtags?: string[]
  domains: string[]
  domainSuffixes?: string[]
  titleKeywords: string[]
  urlPatterns?: string[]
  queryPatterns?: string[]
  priority?: number
}

export const TAG_RULES: TagRule[] = [
  {
    tag: 'social',
    subtags: ['instantMessaging', 'communityForum', 'professionalSocial', 'photoSocial'],
    domains: [
      'twitter.com', 'x.com', 'weibo.com', 'facebook.com', 'instagram.com', 'reddit.com',
      'douban.com', 'linkedin.com', 'mastodon.social', 'threads.net', 'tumblr.com',
      'zhihu.com', 'tieba.baidu.com', 'discord.com', 'telegram.org', 'slack.com',
      'clubhouse.com', 'vk.com', 'snapchat.com', 'xiaohongshu.com', 'pinterest.com',
      'quora.com', 'stackexchange.com', 'zhihuishu.com', 'weixin.qq.com', 'wx.qq.com',
      'web.wechat.com', 'messenger.com', 'whatsapp.com', 'web.whatsapp.com',
      'line.me', 'kakao.com', 'signal.org', 'teams.microsoft.com', 'skype.com',
      'icq.com', 'irc', 'gitter.im', 'matrix.org', 'element.io',
      'bluesky.social', 'bsky.app', 'cohost.org', 'post.news',
      'misskey.io', 'pleroma.social', 'friendica', 'diaspora',
    ],
    domainSuffixes: ['.social', '.chat', '.moe'],
    titleKeywords: [
      '社交', 'social', '关注', '粉丝', '动态', '朋友圈', '帖子', '讨论',
      '私信', '群聊', '好友', '评论', '转发', '点赞', '关注',
      'inbox', 'message', 'chat', 'follow', 'follower',
    ],
    urlPatterns: ['/feed', '/timeline', '/status/', '/post/', '/comment/', '/messages/', '/dm/', '/chat/'],
    queryPatterns: ['tab=messages', 'action=chat', 'view=feed'],
    priority: 8,
  },
  {
    tag: 'video',
    subtags: ['shortVideo', 'longVideo', 'liveStream', 'streaming'],
    domains: [
      'youtube.com', 'bilibili.com', 'netflix.com', 'vimeo.com', 'tiktok.com', 'douyin.com',
      'hulu.com', 'disneyplus.com', 'primevideo.com', 'hbomax.com', 'iqiyi.com', 'youku.com',
      'mgtv.com', 'acfun.cn', 'nicovideo.jp', 'dailymotion.com',
      'twitch.tv', 'live.bilibili.com', 'douyu.com', 'huya.com', 'cc.163.com',
      'peertube', 'odysee.com', 'rumble.com', 'kick.com', 'trovo.live',
      'youtube.com/shorts', 'youtube.com/live',
      'crunchyroll.com', 'funimation.com', 'vrv.co', 'animelab.com',
      'paramountplus.com', 'peacocktv.com', 'appletv.apple.com',
      'm.youtube.com', 'studio.youtube.com',
      'v.qq.com', 'v.youku.com', 'film.sohu.com', 'tv.sohu.com',
      'le.com', 'pptv.com', 'wasu.cn',
    ],
    domainSuffixes: ['.tv'],
    titleKeywords: [
      '视频', 'video', 'watch', '直播', 'live', '番剧', '动漫', '动画',
      'movie', 'film', '剧集', '综艺', '短视频', 'vlog', 'stream',
      '纪录片', 'documentary', '预告', 'trailer', '弹幕', 'danmaku',
    ],
    urlPatterns: ['/watch', '/video/', '/live/', '/play/', '/episode/', '/shorts/', '/stream/', '/clip/'],
    queryPatterns: ['v=', 'video_id=', 'bvid=', 'aid=', 'ep_id='],
    priority: 9,
  },
  {
    tag: 'tech',
    subtags: ['frontend', 'backend', 'mobile', 'devops', 'database', 'security', 'opensource'],
    domains: [
      'github.com', 'gitlab.com', 'bitbucket.org', 'stackoverflow.com', 'stackexchange.com',
      'developer.mozilla.org', 'npmjs.com', 'pypi.org', 'crates.io', 'rubygems.org',
      'csdn.net', 'juejin.cn', 'segmentfault.com', 'dev.to', 'hashnode.dev', 'hackernoon.com',
      'news.ycombinator.com', 'lobste.rs', 'v2ex.com', 'infoq.cn', 'oschina.net',
      'cnblogs.com', 'iteye.com', '51cto.com', 'linux.cn', 'rust-lang.org',
      'python.org', 'nodejs.org', 'go.dev', 'vuejs.org', 'react.dev', 'angular.io',
      'webpack.js.org', 'vitejs.dev', 'typescriptlang.org', 'docs.rs',
      'pkg.go.dev', 'docs.python.org', 'kubernetes.io', 'docker.com',
      'aws.amazon.com', 'cloud.google.com', 'azure.microsoft.com',
      'digitalocean.com', 'heroku.com', 'vercel.com', 'netlify.app',
      'cloudflare.com', 'firebase.google.com', 'supabase.com',
      'codepen.io', 'codesandbox.io', 'jsfiddle.net', 'replit.com',
      'leetcode.com', 'codeforces.com', 'hackerrank.com', 'codewars.com',
      'atcoder.jp', 'topcoder.com', 'spoj.com', 'projecteuler.net',
      'svelte.dev', 'nextjs.org', 'nuxt.com', 'astro.build', 'remix.run',
      'tailwindcss.com', 'unocss.dev', 'mui.com', 'ant.design',
      'expressjs.com', 'fastapi.tiangolo.com', 'django.com', 'flask.palletsprojects.com',
      'spring.io', 'laravel.com', 'rails.org', 'gin-gonic.com',
      'mongodb.com', 'redis.com', 'postgresql.org', 'mysql.com',
      'elastic.co', 'grafana.com', 'prometheus.io', 'jenkins.io',
      'owasp.org', 'portswigger.net', 'hackthebox.com', 'tryhackme.com',
      'android.com/developers', 'developer.apple.com', 'developer.android.com',
      'docs.flutter.dev', 'reactnative.dev', 'capacitorjs.com',
      'deno.land', 'bun.sh', 'prisma.io', 'drizzle.team',
      'trpc.io', 'graphql.org', 'hasura.io', 'supabase.com/docs',
    ],
    domainSuffixes: ['.dev', '.io', '.rs', '.sh', '.app'],
    titleKeywords: [
      'api', 'sdk', '代码', '编程', '开发', 'debug', 'react', 'vue', 'python', 'typescript',
      'javascript', 'rust', 'golang', 'java', 'c++', '算法', '数据结构', '框架', '库',
      '部署', 'deploy', '容器', 'docker', 'k8s', '微服务', 'serverless',
      '前端', '后端', 'fullstack', 'devops', 'ci/cd', 'git', '数据库',
      '编程题', '刷题', 'leetcode', 'oj', '竞赛', 'runtime', 'compiler',
      'middleware', 'orm', 'cache', 'queue', 'websocket', 'grpc',
      'component', 'hook', 'state', 'render', 'bundle', 'webpack', 'vite',
      'sql', 'nosql', 'migration', 'schema', 'index', 'query',
      'authentication', 'authorization', 'jwt', 'oauth', 'cors',
      'ssh', 'tls', 'ssl', 'encryption', 'vulnerability', 'xss', 'csrf',
    ],
    urlPatterns: [
      '/issues/', '/pull/', '/commit/', '/blob/', '/tree/', '/releases/',
      '/questions/', '/answers/', '/tags/', '/repos/', '/packages/',
      '/api/', '/sdk/', '/cli/', '/config/', '/env/',
    ],
    queryPatterns: ['tab=repositories', 'q=repo', 'sort=stars', 'language='],
    priority: 9,
  },
  {
    tag: 'docs',
    subtags: ['collaboration', 'knowledgeBase', 'apiDocs', 'notes'],
    domains: [
      'docs.google.com', 'notion.so', 'notion.site', 'confluence', 'wiki',
      'readthedocs.io', 'gitbook.com', 'docusaurus.io', 'mkdocs.org',
      'swagger.io', 'postman.com', 'insomnia.rest', 'typora.io',
      'feishu.cn', 'dingtalk.com', 'yuque.com', 'shimo.im', 'mubu.com',
      'processon.com', 'draw.io', 'miro.com', 'lucidchart.com',
      'coda.io', 'airtable.com', 'clickup.com', 'asana.com',
      'atlassian.net', 'atlassian.com', 'jira', 'trello.com',
      'obsidian.md', 'logseq.com', 'roamresearch.com',
      'craft.do', 'bear.app', 'ulysses.app', 'ia.net',
      'dropbox.com', 'drive.google.com', 'onedrive.com',
      'overleaf.com', 'sharelatex.com', 'latex',
      'hackmd.io', 'markmap.js.org', 'mindmup.com',
    ],
    titleKeywords: [
      '文档', 'docs', 'documentation', '手册', '指南', 'wiki', '知识库', '笔记', '协作',
      '规范', '标准', 'rfc', 'specification', 'markdown', 'latex', '表格',
      'spreadsheet', 'presentation', 'slides', '模板', 'template',
    ],
    urlPatterns: ['/docs/', '/wiki/', '/guide/', '/manual/', '/reference/', '/handbook/', '/note/', '/page/'],
    queryPatterns: ['edit=', 'view=edit', 'mode=edit'],
    priority: 7,
  },
  {
    tag: 'shopping',
    subtags: ['ecommerce', 'priceComparison', 'secondhand', 'brand'],
    domains: [
      'taobao.com', 'jd.com', 'amazon.com', 'pinduoduo.com', 'tmall.com', 'ebay.com',
      'suning.com', 'vip.com', 'kaola.com', 'mi.com', 'apple.com/shop',
      'walmart.com', 'target.com', 'bestbuy.com', 'costco.com',
      'shein.com', 'shopee.com', 'lazada.com', 'aliexpress.com',
      'etsy.com', 'zara.com', 'uniqlo.com', 'nike.com', 'adidas.com',
      'smzdm.com', 'manmanbuy.com', 'gwdang.com',
      'xianyu.com', 'idle.taobao.com', 'poizon.com', 'zhuanzhuan.com',
      'dangdang.com', 'yanxuan.com', 'you.163.com',
      'samsung.com', 'huawei.com', 'oppo.com', 'vivo.com',
      'newegg.com', 'microcenter.com', 'bhphotovideo.com',
      'farfetch.com', 'ssense.com', 'matchesfashion.com',
      'sephora.com', 'macys.com', 'nordstrom.com',
      'mercari.com', 'rakuten.co.jp', 'yahoo.co.jp/shopping',
    ],
    domainSuffixes: ['.shop', '.store', '.market'],
    titleKeywords: [
      '购买', '价格', '优惠', '折扣', '秒杀', '优惠券', '比价', '包邮', '下单', '购物车',
      '促销', '特价', '打折', '满减', '好价', '值得买', 'review', '测评',
      '开箱', 'unboxing', '种草', '拔草', '正品', '假货', '物流', '快递',
    ],
    urlPatterns: ['/product/', '/item/', '/cart', '/checkout', '/order/', '/deal/', '/coupon/', '/shop/', '/goods/'],
    queryPatterns: ['item_id=', 'product_id=', 'sku=', 'spu=', 'category_id='],
    priority: 8,
  },
  {
    tag: 'news',
    subtags: ['techNews', 'financeNews', 'international', 'society'],
    domains: [
      'news.ycombinator.com', 'bbc.com', 'cnn.com', 'sina.com.cn', '163.com', 'thepaper.cn',
      'reuters.com', 'apnews.com', 'nytimes.com', 'washingtonpost.com', 'theguardian.com',
      'wsj.com', 'ft.com', 'economist.com', 'time.com', 'newsweek.com',
      'ifeng.com', 'sohu.com', 'qq.com/news', 'caixin.com', 'jiemian.com',
      'guancha.cn', 'zaobao.com', 'chinadaily.com.cn', 'people.com.cn',
      'xinhuanet.com', 'cctv.com', 'ithome.com', '36kr.com', 'huxiu.com',
      'tmtpost.com', 'ifanr.com', 'cnbeta.com', 'solidot.org',
      'aljazeera.com', 'dw.com', 'france24.com', 'nhk.or.jp',
      'foxnews.com', 'nbcnews.com', 'abcnews.go.com', 'cbsnews.com',
      'apnews.com', 'usatoday.com', 'npr.org', 'bbc.co.uk',
      'theverge.com', 'wired.com', 'arstechnica.com', 'techcrunch.com',
      'engadget.com', 'gizmodo.com', 'mashable.com',
      'zaobao.com.sg', 'scmp.com', 'thestraitstimes.com',
    ],
    titleKeywords: [
      '新闻', 'news', '报道', '快讯', '头条', '突发', '时事', '热点', '评论', '社论',
      'breaking', 'headline', 'exclusive', '深度', '调查', '专题',
    ],
    urlPatterns: ['/news/', '/article/', '/story/', '/breaking/', '/headline/', '/report/', '/column/'],
    queryPatterns: ['section=news', 'category=news', 'type=article'],
    priority: 7,
  },
  {
    tag: 'design',
    subtags: ['uiux', 'graphic', '3d', 'motion', 'assets'],
    domains: [
      'dribbble.com', 'behance.net', 'figma.com', 'canva.com', 'unsplash.com', 'pinterest.com',
      'adobe.com', 'sketch.com', 'invisionapp.com', 'framer.com', 'spline.design',
      'coolors.co', 'color.adobe.com', 'fontawesome.com', 'fonts.google.com',
      'iconfont.cn', 'iconify.design', 'flaticon.com', 'iconfinder.com',
      'shutterstock.com', 'gettyimages.com', 'pexels.com', 'pixabay.com',
      'freepik.com', 'awwwards.com', 'cssdesignawards.com',
      'zcool.com.cn', 'uisdc.com', 'seeseed.com',
      'blender.org', 'sketchfab.com', 'poly.food', 'threejs.org',
      'lottiefiles.com', 'rive.app', 'haiku.ai',
      'penpot.app', 'plasmic.app', 'webflow.com', 'bubble.io',
      'creativemarket.com', 'envato.com', 'themeforest.net',
      'dribbble.com/shots', 'mobbin.com', 'pageflows.com',
    ],
    domainSuffixes: ['.design', '.art'],
    titleKeywords: [
      '设计', 'design', 'ui', 'ux', '配色', '字体', '排版', '原型', '交互', '视觉',
      'icon', '插画', 'illustration', 'mockup', 'wireframe', 'gradient',
      'figma', 'sketch', '组件', 'component', 'token', '色板', 'palette',
      '响应式', 'responsive', '动画', 'motion', '3d', '建模',
    ],
    urlPatterns: ['/design/', '/prototype/', '/canvas/', '/editor/', '/template/', '/shot/', '/portfolio/'],
    queryPatterns: ['file=', 'node-id=', 'type=design'],
    priority: 7,
  },
  {
    tag: 'learning',
    subtags: ['courses', 'academic', 'language', 'codingLearning'],
    domains: [
      'coursera.org', 'udemy.com', 'khan', 'edu.cn', 'mooc',
      'edx.org', 'mit.edu', 'stanford.edu', 'harvard.edu', 'ocw.mit.edu',
      'skillshare.com', 'pluralsight.com', 'linkedin.com/learning',
      'duolingo.com', 'babbel.com', 'rosettastone.com',
      'icourse163.org', 'xuetangx.com', 'imooc.com', 'jikexueyuan.com',
      'runoob.com', 'w3schools.com', 'tutorialspoint.com', 'geeksforgeeks.org',
      'brilliant.org', 'khanacademy.org', 'scratch.mit.edu',
      'scholar.google.com', 'arxiv.org', 'researchgate.net', 'semanticscholar.org',
      'academia.edu', 'core.ac.uk', 'doi.org', 'springer.com', 'ieee.org',
      'udacity.com', 'datacamp.com', 'codecademy.com',
      'futurelearn.com', 'coursera.org', 'khanacademy.org',
      'quizlet.com', 'ankiweb.net', 'memrise.com',
      'z-library.org', 'libgen.is', 'sci-hub',
    ],
    domainSuffixes: ['.edu', '.ac.uk', '.ac.jp'],
    titleKeywords: [
      '教程', 'tutorial', '课程', 'course', '学习', '入门', '进阶', '实战', '培训',
      '论文', 'paper', '研究', 'research', '学术', 'academic', '学位', 'thesis',
      '考试', 'exam', '认证', 'certification', '练习', 'exercise', 'quiz',
    ],
    urlPatterns: ['/learn/', '/course/', '/lesson/', '/lecture/', '/tutorial/', '/paper/', '/class/'],
    queryPatterns: ['course_id=', 'lesson=', 'chapter='],
    priority: 8,
  },
  {
    tag: 'email',
    domains: [
      'mail.google.com', 'outlook.com', 'outlook.live.com', 'mail.qq.com', 'mail.163.com',
      'mail.yahoo.com', 'proton.me', 'protonmail.com', 'zoho.com/mail',
      'fastmail.com', 'tutanota.com', 'gmx.com', 'mail.ru',
      'mail.sina.com', 'mail.126.com', 'mail.sohu.com', 'ym.163.com',
      'mail.139.com', 'mail.exmail.qq.com',
    ],
    titleKeywords: ['邮件', 'email', 'inbox', '收件箱', '发件', 'draft', 'sent'],
    urlPatterns: ['/mail/', '/inbox/', '/compose/'],
    priority: 6,
  },
  {
    tag: 'music',
    subtags: ['streaming', 'podcast', 'lyrics'],
    domains: [
      'spotify.com', 'music.163.com', 'soundcloud.com', 'apple.com/music',
      'music.apple.com', 'tidal.com', 'deezer.com', 'pandora.com',
      'y.qq.com', 'kugou.com', 'kuwo.cn', 'xiami.com',
      'bandcamp.com', 'last.fm', 'genius.com', 'azlyrics.com',
      'music.youtube.com', 'audius.co', 'reverbnation.com',
      'podcasts.apple.com', 'podcasts.google.com', 'overcast.fm',
      'pocketcasts.com', 'castro.fm', 'breakers.fm',
      'kuaishou.com', '5sing.kugou.com',
    ],
    domainSuffixes: ['.fm', '.radio'],
    titleKeywords: [
      '音乐', 'music', 'playlist', '歌单', '专辑', 'album', '歌词', 'lyrics',
      '播客', 'podcast', '单曲', '歌手', 'singer', 'band',
    ],
    urlPatterns: ['/track/', '/album/', '/playlist/', '/artist/', '/podcast/', '/song/'],
    queryPatterns: ['id=', 'track=', 'album='],
    priority: 7,
  },
  {
    tag: 'ai',
    subtags: ['chat', 'imageGeneration', 'model', 'aiTools'],
    domains: [
      'chat.openai.com', 'chatgpt.com', 'claude.ai', 'gemini.google.com', 'huggingface.co',
      'midjourney.com', 'perplexity.ai', 'poe.com', 'character.ai',
      'stability.ai', 'runwayml.com', 'replicate.com', 'together.ai',
      'anthropic.com', 'openai.com', 'deepmind.com', 'deepmind.google',
      'copilot.microsoft.com', 'bing.com/chat', 'bard.google.com',
      'civitai.com', 'ollama.com', 'langchain.com', 'lmstudio.ai',
      'chat.zhipu.ai', 'yiyan.baidu.com', 'tongyi.aliyun.com',
      'xinghuo.xfyun.cn', 'kimi.moonshot.cn', 'doubao.com',
      'tiangong.cn', 'baichuan-ai.com', 'minimaxi.com',
      'suno.com', 'udio.com', 'elevenlabs.io',
      'leonardo.ai', 'playground.ai', 'nightcafe.studio',
      'huggingface.co/spaces', 'huggingface.co/models',
      'openrouter.ai', 'groq.com', 'cerebras.ai', 'sambanova.ai',
      'dify.ai', 'coze.com', 'fastgpt.in', 'lobechat.com',
      'cursor.com', 'windsurf.ai', 'augmentcode.com',
      'v0.dev', 'bolt.new', 'lovable.dev', 'replit.com/ai',
      'comfyui.com', 'automatic1111.com', 'fooocus.ai',
    ],
    titleKeywords: [
      'chatgpt', 'gpt', 'ai', '人工智能', 'llm', 'prompt', '大模型', '生成式',
      'diffusion', 'transformer', 'neural', '机器学习', '深度学习',
      'stable diffusion', 'midjourney', 'dall-e', 'copilot',
      'embedding', 'fine-tune', 'rag', 'agent', 'chain-of-thought',
      '文生图', '图生图', '文生视频', 'ai绘画', 'ai写作',
    ],
    urlPatterns: ['/chat/', '/generate/', '/model/', '/inference/', '/completions/', '/playground/'],
    queryPatterns: ['model=', 'prompt=', 'q=', 'chat='],
    priority: 10,
  },
  {
    tag: 'gaming',
    subtags: ['pc', 'console', 'mobileGame', 'guide', 'esports'],
    domains: [
      'store.steampowered.com', 'steampowered.com', 'epicgames.com', 'playstation.com',
      'xbox.com', 'twitch.tv', 'nintendo.com', 'gog.com', 'origin.com',
      'blizzard.com', 'riotgames.com', 'ubisoft.com', 'ea.com',
      'taptap.com', '4399.com', '7k7k.com', '3dmgame.com',
      'ign.com', 'gamespot.com', 'polygon.com', 'kotaku.com',
      'nexusmods.com', 'moddb.com', 'curseforge.com',
      'speedrun.com', 'howlongtobeat.com', 'metacritic.com',
      'op.gg', 'u.gg', 'mobafire.com', 'lol.qq.com',
      'pvp.qq.com', 'cg.163.com', 'hs.blizzard.com',
      'playvalorant.com', 'playapex.com', 'playoverwatch.com',
      'genshin.hoyoverse.com', 'hoyolab.com', 'starrail.hoyoverse.com',
      'roblox.com', 'mojang.com', 'minecraft.net',
      'gamefaqs.gamespot.com', 'trueachievements.com',
      'deckbuilder', 'mmorpg.com', 'rockpapershotgun.com',
      'biligame.com', 'game.bilibili.com',
    ],
    domainSuffixes: ['.gg'],
    titleKeywords: [
      '游戏', 'game', 'gaming', '攻略', 'walkthrough', 'mod', '通关', '副本',
      'fps', 'rpg', 'moba', '开放世界', '角色扮演', 'steam',
      '电竞', 'esports', '排位', 'ranked', '赛季', 'season',
      '抽卡', 'gacha', '装备', 'build', '天赋', 'skill',
    ],
    urlPatterns: ['/game/', '/app/', '/store/', '/play/', '/mods/', '/wiki/'],
    queryPatterns: ['app_id=', 'game_id=', 'rank='],
    priority: 8,
  },
  {
    tag: 'finance',
    subtags: ['stocks', 'crypto', 'funds', 'banking'],
    domains: [
      'bloomberg.com', 'finance.yahoo.com', 'xueqiu.com', 'eastmoney.com',
      'coinmarketcap.com', 'binance.com', 'okx.com', 'huobi.com',
      'tradingview.com', 'investing.com', 'seekingalpha.com',
      'robinhood.com', 'fidelity.com', 'vanguard.com', 'schwab.com',
      'wallstreetcn.com', 'jinse.com', '8btc.com', 'mifengcha.com',
      'fund.eastmoney.com', 'laohu8.com', 'longbridgeapp.com',
      'rich.baidu.com', 'finance.sina.com.cn', 'stock.xueqiu.com',
      'icbc.com.cn', 'ccb.com', 'boc.cn', 'abchina.com', 'bankcomm.com',
      'cmbchina.com', 'spdb.com.cn', 'cib.com.cn',
      'paypal.com', 'wise.com', 'revolut.com',
      'coinbase.com', 'kraken.com', 'gate.io', 'bybit.com',
      'dune.com', 'defillama.com', 'etherscan.io', 'bscscan.com',
    ],
    titleKeywords: [
      '股票', '基金', '投资', '行情', '加密', 'crypto', 'bitcoin', 'btc', 'eth',
      '区块链', 'blockchain', 'defi', 'nft', '交易', 'trading', 'k线',
      '估值', '财报', 'ipo', '市值', '涨幅', '跌幅', '涨停',
      '利率', '通胀', '美联储', 'fed', 'bond', '期货', 'futures',
    ],
    urlPatterns: ['/quote/', '/stock/', '/crypto/', '/trade/', '/portfolio/', '/market/', '/fund/'],
    queryPatterns: ['symbol=', 'ticker=', 'pair='],
    priority: 8,
  },
  {
    tag: 'blog',
    subtags: ['techBlog', 'personalBlog', 'column'],
    domains: [
      'medium.com', 'substack.com', 'wordpress.com', 'ghost.org',
      'dev.to', 'hashnode.dev', 'hackernoon.com',
      'blog.cloudflare.com', 'blog.google', 'netflixtechblog.com',
      'engineering.fb.com', 'twobithistory.org', 'danluu.com',
      'paulgraham.com', 'blog.ycombinator.com', 'martinfowler.com',
      'joelonsoftware.com', 'vercel.com/blog', 'stripe.com/blog',
      'shopify.engineering', 'uber.com/blog',
      'cnblogs.com', 'iteye.com', 'oschina.net/blog',
      'sspai.com', 'ruanyifeng.com', 'coolshell.cn',
      'overreacted.io', 'kentcdodds.com', 'joshwcomeau.com',
    ],
    titleKeywords: ['博客', 'blog', '博文', '随笔', '思考', '心得', '经验分享', '踩坑', '专栏', 'column'],
    urlPatterns: ['/blog/', '/post/', '/article/', '/archive/', '/essays/'],
    priority: 5,
  },
  {
    tag: 'forum',
    subtags: ['techCommunity', 'interestCommunity', 'qna'],
    domains: [
      'v2ex.com', 'reddit.com', 'tieba.baidu.com',
      'douban.com/group', 'nga.cn', 'nga.178.com', 'colg.cn',
      'bbs.nga.cn', 'hostloc.com', 'linux.do',
      'testerhome.com', 'ruby-china.org', 'elixir-cn.org',
      'golangtc.com', 'python-china.org', 'cnodejs.org',
      '4chan.org', '8kun.top', 'discourse',
      'lesswrong.com', 'effectivealtruism.org',
      'chiphell.com', 'bbs.pcbeta.com', 'bbs.kafan.cn',
    ],
    domainSuffixes: ['.forum'],
    titleKeywords: ['论坛', 'forum', '社区', 'community', '讨论区', '板块', '帖子', '回帖', '问答', 'q&a'],
    urlPatterns: ['/forum/', '/board/', '/thread/', '/topic/', '/t/', '/c/', '/r/'],
    priority: 6,
  },
  {
    tag: 'tools',
    subtags: ['devTools', 'productivityTools', 'converterTools'],
    domains: [
      'translate.google.com', 'deepl.com', 'grammarly.com',
      '1password.com', 'bitwarden.com', 'lastpass.com',
      'wolframalpha.com', 'desmos.com', 'geogebra.org',
      'regex101.com', 'jsonformatter.org', 'codebeautify.org',
      'caniuse.com', 'bundlephobia.com', 'npm.anvaka.com',
      'speedtest.net', 'fast.com', 'whatismyip.com',
      'remove.bg', 'tinypng.com', 'squoosh.app', 'compressor.io',
      'carbon.now.sh', 'ray.so', 'snappify.com',
      'excalidraw.com', 'tldraw.com', 'whimsical.com',
      'mermaid.live', 'plantuml.com', 'websequencediagrams.com',
      'diffchecker.com', 'vim-adventures.com', 'typing.com',
      'jwt.io', 'base64encode.org', 'urlencoder.org',
      'cyberchef.org', 'gchq.github.io/CyberChef',
      'transform.tools', 'convertio.co', 'cloudconvert.com',
      'pdf24.org', 'ilovepdf.com', 'smallpdf.com',
      'temp-mail.org', 'guerrillamail.com',
      'downforeveryoneorjustme.com', 'isitdownrightnow.com',
    ],
    titleKeywords: [
      '工具', 'tool', '转换', 'converter', '计算器', 'calculator', '生成器', 'generator',
      '格式化', 'formatter', '压缩', 'compress', '加密', 'decrypt', 'encrypt',
      '编码', 'decode', 'encode', '校验', 'validate', '解析', 'parse',
    ],
    urlPatterns: ['/tool/', '/utils/', '/convert/', '/generate/', '/calculate/', '/format/', '/encode/'],
    priority: 6,
  },
  {
    tag: 'cloud',
    subtags: ['cloudPlatform', 'monitoring', 'cdn', 'serverless'],
    domains: [
      'console.aws.amazon.com', 'console.cloud.google.com', 'portal.azure.com',
      'dash.cloudflare.com', 'app.vercel.com', 'app.netlify.com',
      'dashboard.heroku.com', 'console.firebase.google.com',
      'manage.digitalocean.com', 'app.supabase.com',
      'oci.oraclecloud.com', 'console.alibabacloud.com',
      'console.tencentcloud.com', 'console.huaweicloud.com',
      'dashboard.stripe.com', 'dashboard.paypal.com',
      'analytics.google.com', 'search.google.com/search-console',
      'app.datadoghq.com', 'app.newrelic.com', 'grafana.com',
      'sentry.io', 'logrocket.com', 'pagerduty.com',
      'updown.io', 'pingdom.com', 'statuspage.io',
      'railway.app', 'render.com', 'fly.io',
      'planetscale.com', 'neon.tech', 'cockroachlabs.com',
      'turso.tech', 'xata.io', 'nhost.io',
    ],
    titleKeywords: [
      '云服务', 'cloud', '部署', 'deploy', '运维', 'devops', '监控', 'monitoring',
      '服务器', 'server', '域名', 'dns', 'cdn', '负载均衡', 'load balancer',
    ],
    urlPatterns: ['/console/', '/dashboard/', '/admin/', '/manage/', '/portal/', '/project/'],
    priority: 7,
  },
  {
    tag: 'health',
    subtags: ['medical', 'fitness', 'mental', 'diet'],
    domains: [
      'webmd.com', 'mayoclinic.org', 'healthline.com', 'nih.gov',
      'who.int', 'cdc.gov', 'medlineplus.gov',
      'dxy.com', 'chunyuyisheng.com', 'guahao.com',
      'keep.com', 'codoon.com', 'joyrun.com',
      'myfitnesspal.com', 'strava.com', 'fitbit.com',
      'calm.com', 'headspace.com', 'noom.com',
      'peloton.com', 'nike.com/nrc', 'adidas.com/running',
      'bodybuilding.com', 'muscleandstrength.com',
      'psychologytoday.com', 'betterhelp.com', 'talkspace.com',
    ],
    titleKeywords: [
      '健康', 'health', '医疗', '医学', '症状', '诊断', '养生', '运动', 'fitness',
      '减肥', '饮食', '营养', '睡眠', '心理', '冥想', 'meditation',
      '卡路里', 'calorie', '增肌', '减脂', '有氧', '无氧',
    ],
    urlPatterns: ['/health/', '/medical/', '/symptom/', '/fitness/', '/workout/', '/exercise/'],
    priority: 5,
  },
  {
    tag: 'travel',
    subtags: ['flights', 'hotels', 'travelGuide', 'visa'],
    domains: [
      'booking.com', 'airbnb.com', 'tripadvisor.com', 'expedia.com',
      'ctrip.com', 'qunar.com', 'mafengwo.cn', 'tuniu.com',
      'agoda.com', 'hotels.com', 'priceline.com',
      'skyscanner.com', 'kayak.com', 'google.com/travel',
      'rome2rio.com', 'lonelyplanet.com', 'wikivoyage.org',
      'viator.com', 'getyourguide.com', 'klook.com',
      'hostelworld.com', 'couchsurfing.com',
    ],
    titleKeywords: [
      '旅行', 'travel', '旅游', '机票', '酒店', '民宿', '景点', '攻略', '签证',
      'flight', 'hotel', 'booking', 'vacation', '度假', '行程', 'itinerary',
    ],
    urlPatterns: ['/travel/', '/hotel/', '/flight/', '/booking/', '/destination/', '/attraction/'],
    priority: 5,
  },
  {
    tag: 'food',
    subtags: ['delivery', 'recipes', 'restaurant', 'drinks'],
    domains: [
      'meituan.com', 'ele.me', 'dianping.com',
      'yelp.com', 'opentable.com', 'just-eat.com', 'deliveroo.com',
      'ubereats.com', 'doordash.com', 'grubhub.com',
      'xiachufang.com', 'cookpad.com', 'allrecipes.com',
      'foodnetwork.com', 'seriouseats.com', 'bonappetit.com',
      'starbucks.com', 'luckincoffee.com',
    ],
    titleKeywords: [
      '美食', '食谱', 'recipe', '烹饪', 'cooking', '餐厅', 'restaurant', '外卖',
      '菜单', 'menu', '烘焙', 'baking', '料理', '小吃', '咖啡', 'coffee',
    ],
    urlPatterns: ['/recipe/', '/restaurant/', '/food/', '/menu/', '/dish/'],
    priority: 5,
  },
  {
    tag: 'government',
    subtags: ['governmentAffairs', 'transportation', 'tax', 'socialSecurity'],
    domains: [
      'gov.cn', 'gov.uk', 'usa.gov', 'whitehouse.gov',
      'nhs.uk', 'irs.gov', 'ssa.gov',
      '12306.cn', 'gjj.beijing.gov.cn', 'bjzwfw.gov.cn',
      'shanghai.gov.cn', 'gd.gov.cn', 'sz.gov.cn',
      'nhs.uk', 'service.gov.uk', 'usa.gov',
      'chengdu.gov.cn', 'hangzhou.gov.cn', 'nanjing.gov.cn',
      'chongqing.gov.cn', 'tianjin.gov.cn', 'wuhan.gov.cn',
    ],
    domainSuffixes: ['.gov', '.gov.cn', '.gov.uk', '.gov.us'],
    titleKeywords: ['政府', '政务', '办事', '公积金', '社保', '税务', '工商', '民政', '户籍', '护照', '签证'],
    urlPatterns: ['/gov/', '/public/', '/service/', '/portal/', '/zwfw/'],
    priority: 4,
  },
  {
    tag: 'search',
    domains: [
      'google.com', 'google.com.hk', 'baidu.com', 'bing.com', 'sogou.com',
      'so.com', 'duckduckgo.com', 'yandex.com', 'ecosia.org',
      'search.yahoo.com', 'startpage.com', 'brave.com/search',
      'google.co.jp', 'google.co.kr', 'google.de', 'google.fr',
    ],
    titleKeywords: ['搜索', 'search', '查找', 'query', '搜索结果'],
    urlPatterns: ['/search?', '/s?', '/webhp?', '/results', '/search/'],
    queryPatterns: ['q=', 'query=', 'wd=', 'word=', 'text='],
    priority: 3,
  },
  {
    tag: 'reading',
    subtags: ['novel', 'info', 'rss'],
    domains: [
      'readwise.io', 'pocket.com', 'instapaper.com', 'readability.com',
      'feedly.com', 'inoreader.com', 'theoldreader.com', 'miniflux',
      'qidian.com', 'jjwxc.net', 'zongheng.com', '17k.com',
      'kindle.amazon.com', 'goodreads.com', 'book.douban.com',
      'z-library.org', 'gutenberg.org', 'archive.org',
      'weread.qq.com', 'duokan.com', 'dushu.baidu.com',
      'medium.com', 'substack.com', 'sspai.com',
    ],
    titleKeywords: [
      '阅读', 'reading', '小说', 'novel', '书评', 'book review',
      '章节', 'chapter', '连载', 'serial', 'rss', '订阅', 'subscribe',
    ],
    urlPatterns: ['/read/', '/book/', '/chapter/', '/article/', '/feed/', '/novel/'],
    priority: 5,
  },
  {
    tag: 'dev',
    subtags: ['ide', 'cicd', 'testing'],
    domains: [
      'github.com', 'gitlab.com', 'bitbucket.org',
      'code.visualstudio.com', 'jetbrains.com', 'eclipse.org',
      'circleci.com', 'travis-ci.org', 'github.com/features/actions',
      'jenkins.io', 'buildkite.com', 'teamcity',
      'sonarqube.org', 'snyk.io', 'codacy.com',
      'browserstack.com', 'saucelabs.com', 'cypress.io',
      'playwright.dev', 'selenium.dev',
      'figma.com/dev', 'storybook.js.org',
      'linear.app', 'shortcut.com', 'jira.atlassian.net',
    ],
    titleKeywords: [
      'ide', '编辑器', 'editor', '编译', 'compile', '构建', 'build',
      '测试', 'test', '部署', 'deploy', '发布', 'release',
      '代码审查', 'code review', '合并', 'merge', '分支', 'branch',
    ],
    urlPatterns: ['/dev/', '/build/', '/test/', '/deploy/', '/release/', '/pipeline/'],
    priority: 7,
  },
  {
    tag: 'photography',
    subtags: ['gallery', 'postProcessing', 'equipment'],
    domains: [
      'flickr.com', '500px.com', 'unsplash.com', 'pexels.com', 'pixabay.com',
      'adobe.com/lightroom', 'captureone.com', 'darkroom.co',
      'dpreview.com', 'petapixel.com', 'fstoppers.com',
      'lensculture.com', '1x.com', 'viewbug.com',
      'vsco.co', 'lightroom.adobe.com', 'snapseed',
    ],
    titleKeywords: [
      '摄影', 'photography', 'photo', '相机', 'camera', '镜头', 'lens',
      '曝光', 'exposure', '光圈', 'aperture', '快门', 'shutter',
      '后期', 'retouch', '修图', '滤镜', 'filter',
    ],
    urlPatterns: ['/photo/', '/gallery/', '/album/', '/portfolio/', '/shots/'],
    priority: 4,
  },
  {
    tag: 'education',
    subtags: ['k12', 'university', 'gradExam', 'vocational'],
    domains: [
      'edu.cn', 'mooc.cn', 'chaoxing.com', 'xueersi.com',
      'zhangmen.com', 'yuanfudao.com', 'hujiang.com',
      'koolearn.com', 'neworiental.org', 'offcn.com',
      'kaoyan.com', 'chinakaoyan.com',
      'collegeboard.org', 'ets.org', 'ielts.org',
      'toefl.org', 'gre.org',
      'wikipedia.org', 'britannica.com', 'wikihow.com',
    ],
    domainSuffixes: ['.edu'],
    titleKeywords: [
      '教育', 'education', '学校', 'school', '考试', 'exam', '成绩', 'grade',
      '课程', 'curriculum', '学期', 'semester', '招生', 'admission',
      '考研', '考公', '雅思', '托福', 'gre', 'gmat',
    ],
    urlPatterns: ['/edu/', '/school/', '/exam/', '/admission/', '/course/'],
    priority: 6,
  },
  {
    tag: 'sports',
    subtags: ['football', 'basketball', 'esports', 'fitness'],
    domains: [
      'espn.com', 'sports.yahoo.com', 'skysports.com', 'bbc.com/sport',
      'nba.com', 'fifa.com', 'uefa.com',
      'dongqiudi.com', 'zhibo8.com', 'hupu.com',
      '懂球帝', '直播吧', '虎扑',
      'strava.com', 'garmin.com', 'mapmyrun.com',
      'bodybuilding.com', 'muscleandstrength.com',
    ],
    titleKeywords: [
      '体育', 'sport', '足球', 'football', 'soccer', '篮球', 'basketball',
      'nba', '比分', 'score', '联赛', 'league', '冠军', 'champion',
      '奥运', 'olympics', '世界杯', 'world cup',
    ],
    urlPatterns: ['/sport/', '/match/', '/score/', '/league/', '/player/'],
    priority: 4,
  },
  {
    tag: 'automotive',
    subtags: ['carPurchase', 'review', 'maintenance', 'newEnergy'],
    domains: [
      'autohome.com.cn', 'dongchedi.com', 'yiche.com',
      'pcauto.com.cn', 'xcar.com.cn', 'cheshi.com',
      'caranddriver.com', 'motortrend.com', 'edmunds.com',
      'tesla.com', 'byd.com', 'nio.com', 'xiaopeng.com', 'lixiang.com',
      'evspecifications.com', 'insideevs.com',
    ],
    titleKeywords: [
      '汽车', 'car', 'auto', '购车', '买车', '试驾', '评测',
      '电动车', 'ev', '新能源', '充电桩', '续航', '油耗',
      '保养', '维修', '改装', 'suv', '轿车',
    ],
    urlPatterns: ['/car/', '/auto/', '/model/', '/spec/', '/review/'],
    priority: 4,
  },
  {
    tag: 'realestate',
    subtags: ['renting', 'buying', 'renovation'],
    domains: [
      'lianjia.com', 'ke.com', 'anjuke.com', 'fang.com',
      'ziroom.com', 'danke.com', 'mogoroom.com',
      'zillow.com', 'realtor.com', 'redfin.com', 'trulia.com',
      'rightmove.co.uk', 'zoopla.co.uk',
      'tubatu.com', 'qijia.com', 'jia.com',
    ],
    titleKeywords: [
      '房产', '房子', '租房', '买房', '房价', '房贷', '装修',
      'real estate', 'apartment', 'house', 'rent', 'mortgage',
      '二手房', '新房', '楼盘', '户型', '学区房',
    ],
    urlPatterns: ['/house/', '/rent/', '/property/', '/apartment/', '/community/'],
    priority: 4,
  },
  {
    tag: 'law',
    domains: [
      'court.gov.cn', 'wenshu.court.gov.cn', 'chinacourt.org',
      'lawyer.com', 'legalzoom.com', 'avvo.com',
      'findlaw.com', 'justia.com', 'law.cornell.edu',
    ],
    domainSuffixes: ['.law'],
    titleKeywords: [
      '法律', 'law', '律师', 'lawyer', '诉讼', 'litigation',
      '合同', 'contract', '法规', 'regulation', '判例', 'case',
    ],
    urlPatterns: ['/law/', '/legal/', '/case/', '/statute/'],
    priority: 3,
  },
  {
    tag: 'jobs',
    subtags: ['jobSearch', 'resume', 'interview'],
    domains: [
      'zhipin.com', 'liepin.com', '51job.com', 'zhaopin.com',
      'linkedin.com/jobs', 'indeed.com', 'glassdoor.com',
      'monster.com', 'dice.com', 'simplyhired.com',
      'maimai.cn', 'lagou.com', 'neitui.me',
      'angel.co', 'wellfound.com', 'ycombinator.com/jobs',
    ],
    titleKeywords: [
      '招聘', '求职', 'job', 'career', '简历', 'resume', '面试', 'interview',
      '薪资', 'salary', 'offer', '跳槽', '校招', '实习', 'intern',
    ],
    urlPatterns: ['/job/', '/career/', '/position/', '/resume/', '/company/'],
    queryPatterns: ['job_id=', 'position=', 'location='],
    priority: 5,
  },
]

export interface SubtagRule {
  subtag: string
  parentTag: string
  domains?: string[]
  pathKeywords?: string[]
  titleKeywords?: string[]
  productivity: 'productive' | 'neutral' | 'unproductive'
}

export const SUBTAG_RULES: SubtagRule[] = [
  { subtag: 'frontend', parentTag: 'tech', domains: ['vuejs.org', 'react.dev', 'angular.io', 'svelte.dev', 'nextjs.org', 'nuxt.com', 'tailwindcss.com', 'unocss.dev', 'mui.com', 'ant.design', 'vitejs.dev', 'webpack.js.org'], pathKeywords: ['vue', 'react', 'angular', 'svelte', 'css', 'html', 'dom', 'webpack', 'vite', 'component', 'hook', 'render', 'bundle'], titleKeywords: ['前端', 'frontend', 'vue', 'react', 'angular', 'css', '组件', 'component'], productivity: 'productive' },
  { subtag: 'backend', parentTag: 'tech', domains: ['expressjs.com', 'fastapi.tiangolo.com', 'django.com', 'flask.palletsprojects.com', 'spring.io', 'laravel.com', 'gin-gonic.com', 'graphql.org', 'hasura.io', 'trpc.io', 'prisma.io', 'drizzle.team'], pathKeywords: ['api', 'server', 'database', 'rest', 'graphql', 'microservice', 'middleware', 'orm', 'sql', 'nosql'], titleKeywords: ['后端', 'backend', 'api', '数据库', 'server'], productivity: 'productive' },
  { subtag: 'competitiveProgramming', parentTag: 'tech', domains: ['leetcode.com', 'codeforces.com', 'hackerrank.com', 'codewars.com', 'atcoder.jp', 'topcoder.com', 'spoj.com', 'projecteuler.net'], pathKeywords: ['problem', 'contest', 'challenge', 'solution', 'submit'], titleKeywords: ['刷题', 'leetcode', '算法题', '竞赛', 'oj', '编程题'], productivity: 'productive' },
  { subtag: 'devOps', parentTag: 'tech', domains: ['docker.com', 'kubernetes.io', 'jenkins.io', 'grafana.com', 'prometheus.io', 'sentry.io', 'circleci.com'], pathKeywords: ['deploy', 'pipeline', 'container', 'docker', 'k8s', 'ci/cd', 'monitoring'], titleKeywords: ['部署', 'deploy', '运维', 'devops', '容器', 'docker'], productivity: 'productive' },
  { subtag: 'opensource', parentTag: 'tech', domains: ['github.com', 'gitlab.com', 'bitbucket.org', 'npmjs.com', 'pypi.org', 'crates.io'], pathKeywords: ['repos', 'packages', 'issues', 'pull', 'commit', 'releases', 'fork'], titleKeywords: ['开源', 'opensource', '仓库', 'repository', '贡献', 'contributing'], productivity: 'productive' },
  { subtag: 'documentation', parentTag: 'tech', domains: ['developer.mozilla.org', 'docs.rs', 'pkg.go.dev', 'docs.python.org', 'typescriptlang.org', 'readthedocs.io'], pathKeywords: ['docs', 'documentation', 'reference', 'guide', 'manual', 'api-docs'], titleKeywords: ['文档', 'docs', '手册', '指南', 'reference'], productivity: 'productive' },
  { subtag: 'security', parentTag: 'tech', domains: ['owasp.org', 'portswigger.net', 'hackthebox.com', 'tryhackme.com'], pathKeywords: ['vulnerability', 'exploit', 'pentest', 'cve'], titleKeywords: ['安全', 'security', '漏洞', '渗透', 'xss', 'csrf'], productivity: 'productive' },
  { subtag: 'shortVideo', parentTag: 'video', domains: ['tiktok.com', 'douyin.com'], pathKeywords: ['shorts', 'short-video', 'reels'], titleKeywords: ['短视频', 'short video', '抖音', 'tiktok'], productivity: 'unproductive' },
  { subtag: 'longVideo', parentTag: 'video', domains: ['youtube.com', 'bilibili.com', 'netflix.com', 'vimeo.com', 'iqiyi.com', 'youku.com'], pathKeywords: ['watch', 'video', 'episode', 'season'], titleKeywords: ['视频', 'video', '电影', 'movie', '番剧', '纪录片'], productivity: 'unproductive' },
  { subtag: 'liveStream', parentTag: 'video', domains: ['twitch.tv', 'live.bilibili.com', 'douyu.com', 'huya.com'], pathKeywords: ['live', 'stream', 'broadcast'], titleKeywords: ['直播', 'live', 'stream'], productivity: 'unproductive' },
  { subtag: 'instantMessaging', parentTag: 'social', domains: ['discord.com', 'telegram.org', 'slack.com', 'weixin.qq.com', 'web.whatsapp.com', 'messenger.com', 'teams.microsoft.com', 'skype.com'], pathKeywords: ['chat', 'dm', 'messages', 'channel'], titleKeywords: ['聊天', 'chat', '私信', '群聊', '消息'], productivity: 'neutral' },
  { subtag: 'communityForum', parentTag: 'social', domains: ['reddit.com', 'zhihu.com', 'tieba.baidu.com', 'v2ex.com', 'douban.com', 'quora.com', 'stackexchange.com'], pathKeywords: ['forum', 'thread', 'topic', 'post', 'comment', 'discussion'], titleKeywords: ['论坛', '社区', '讨论', '问答', '帖子'], productivity: 'neutral' },
  { subtag: 'professionalSocial', parentTag: 'social', domains: ['linkedin.com'], pathKeywords: ['profile', 'network', 'connection'], titleKeywords: ['职场', '人脉', 'professional'], productivity: 'productive' },
  { subtag: 'photoSocial', parentTag: 'social', domains: ['instagram.com', 'pinterest.com', 'xiaohongshu.com'], pathKeywords: ['photo', 'pin', 'post', 'feed'], titleKeywords: ['图片', '照片', '分享'], productivity: 'unproductive' },
  { subtag: 'onlineCourse', parentTag: 'education', domains: ['coursera.org', 'udemy.com', 'edx.org', 'pluralsight.com', 'skillshare.com', 'udacity.com', 'codecademy.com', 'datacamp.com', 'imooc.com', 'xuetangx.com', 'icourse163.org'], pathKeywords: ['course', 'lesson', 'lecture', 'enroll'], titleKeywords: ['课程', 'course', '在线课', 'mooc'], productivity: 'productive' },
  { subtag: 'selfLearning', parentTag: 'education', domains: ['wikipedia.org', 'wikihow.com', 'runoob.com', 'w3schools.com', 'tutorialspoint.com', 'geeksforgeeks.org', 'brilliant.org', 'khanacademy.org'], pathKeywords: ['wiki', 'learn', 'tutorial', 'guide', 'how-to'], titleKeywords: ['学习', '教程', '入门', '指南', '百科'], productivity: 'productive' },
  { subtag: 'academic', parentTag: 'education', domains: ['scholar.google.com', 'arxiv.org', 'researchgate.net', 'semanticscholar.org', 'academia.edu', 'springer.com', 'ieee.org', 'doi.org'], pathKeywords: ['paper', 'article', 'citation', 'abstract', 'research'], titleKeywords: ['论文', 'paper', '研究', '学术', '期刊'], productivity: 'productive' },
  { subtag: 'ecommerce', parentTag: 'shopping', domains: ['taobao.com', 'jd.com', 'amazon.com', 'pinduoduo.com', 'tmall.com', 'ebay.com', 'walmart.com', 'suning.com', 'vip.com'], pathKeywords: ['product', 'item', 'cart', 'checkout', 'order', 'goods'], titleKeywords: ['购物', '购买', '下单', '商品'], productivity: 'unproductive' },
  { subtag: 'reviews', parentTag: 'shopping', domains: ['smzdm.com', 'zol.com.cn', 'dianping.com'], pathKeywords: ['review', 'rating', 'compare'], titleKeywords: ['测评', '评测', '比价', '推荐'], productivity: 'neutral' },
  { subtag: 'streaming', parentTag: 'music', domains: ['spotify.com', 'music.163.com', 'music.apple.com', 'tidal.com', 'deezer.com', 'y.qq.com', 'kugou.com', 'kuwo.cn'], pathKeywords: ['track', 'album', 'playlist', 'artist', 'song'], titleKeywords: ['音乐', 'music', '歌单', '专辑'], productivity: 'unproductive' },
  { subtag: 'creation', parentTag: 'music', domains: ['soundcloud.com', 'bandcamp.com'], pathKeywords: ['upload', 'create', 'studio'], titleKeywords: ['创作', '原创', '制作'], productivity: 'productive' },
  { subtag: 'pcGaming', parentTag: 'gaming', domains: ['store.steampowered.com', 'epicgames.com', 'gog.com'], pathKeywords: ['store', 'app', 'game', 'library'], titleKeywords: ['steam', 'pc游戏', '单机'], productivity: 'unproductive' },
  { subtag: 'mobileGaming', parentTag: 'gaming', domains: ['taptap.com', '4399.com', '7k7k.com'], pathKeywords: ['mobile', 'android', 'ios'], titleKeywords: ['手游', '手机游戏'], productivity: 'unproductive' },
  { subtag: 'trading', parentTag: 'finance', domains: ['xueqiu.com', 'tradingview.com', 'robinhood.com', 'binance.com', 'coinmarketcap.com', 'okx.com', 'eastmoney.com', 'finance.yahoo.com'], pathKeywords: ['quote', 'stock', 'crypto', 'trade', 'chart', 'kline'], titleKeywords: ['股票', '行情', '交易', 'k线', '加密'], productivity: 'neutral' },
  { subtag: 'banking', parentTag: 'finance', domains: ['icbc.com.cn', 'ccb.com', 'boc.cn', 'cmbchina.com', 'paypal.com', 'wise.com'], pathKeywords: ['account', 'transfer', 'payment'], titleKeywords: ['银行', '转账', '支付'], productivity: 'neutral' },
  { subtag: 'novel', parentTag: 'reading', domains: ['qidian.com', 'jjwxc.net', 'zongheng.com', '17k.com', 'weread.qq.com', 'kindle.amazon.com'], pathKeywords: ['chapter', 'novel', 'book', 'read'], titleKeywords: ['小说', 'novel', '章节', '连载'], productivity: 'unproductive' },
  { subtag: 'articles', parentTag: 'reading', domains: ['medium.com', 'substack.com', 'sspai.com', 'pocket.com', 'readwise.io', 'feedly.com'], pathKeywords: ['article', 'post', 'blog', 'feed'], titleKeywords: ['文章', '阅读', 'rss', '订阅'], productivity: 'neutral' },
  { subtag: 'uiDesign', parentTag: 'design', domains: ['figma.com', 'dribbble.com', 'behance.net', 'framer.com', 'penpot.app', 'sketch.com', 'awwwards.com'], pathKeywords: ['design', 'prototype', 'canvas', 'shot', 'portfolio'], titleKeywords: ['ui', 'ux', '设计', '原型', '交互'], productivity: 'productive' },
  { subtag: 'designTools', parentTag: 'design', domains: ['canva.com', 'adobe.com', 'unsplash.com', 'pexels.com', 'pixabay.com', 'freepik.com'], pathKeywords: ['template', 'asset', 'image', 'icon', 'font'], titleKeywords: ['素材', '模板', '图标', '字体'], productivity: 'productive' },
  { subtag: 'booking', parentTag: 'travel', domains: ['booking.com', 'ctrip.com', 'airbnb.com', 'agoda.com', 'hotels.com', 'qunar.com', 'expedia.com'], pathKeywords: ['booking', 'hotel', 'flight', 'reservation'], titleKeywords: ['预订', '机票', '酒店', '民宿'], productivity: 'neutral' },
  { subtag: 'travelInfo', parentTag: 'travel', domains: ['tripadvisor.com', 'mafengwo.cn', 'lonelyplanet.com', 'wikivoyage.org'], pathKeywords: ['destination', 'attraction', 'guide', 'review'], titleKeywords: ['攻略', '景点', '旅行'], productivity: 'neutral' },
  { subtag: 'delivery', parentTag: 'food', domains: ['meituan.com', 'ele.me', 'ubereats.com', 'doordash.com', 'dianping.com'], pathKeywords: ['order', 'delivery', 'restaurant'], titleKeywords: ['外卖', '配送', '点餐'], productivity: 'neutral' },
  { subtag: 'recipes', parentTag: 'food', domains: ['xiachufang.com', 'cookpad.com', 'allrecipes.com', 'foodnetwork.com', 'seriouseats.com'], pathKeywords: ['recipe', 'cook', 'ingredient', 'dish'], titleKeywords: ['食谱', '烹饪', '做法', '菜谱'], productivity: 'neutral' },
  { subtag: 'fitness', parentTag: 'health', domains: ['keep.com', 'myfitnesspal.com', 'strava.com', 'bodybuilding.com'], pathKeywords: ['workout', 'exercise', 'training', 'fitness'], titleKeywords: ['健身', '运动', '锻炼', '减肥'], productivity: 'neutral' },
  { subtag: 'medical', parentTag: 'health', domains: ['webmd.com', 'mayoclinic.org', 'dxy.com', 'chunyuyisheng.com', 'guahao.com'], pathKeywords: ['symptom', 'diagnosis', 'treatment', 'doctor'], titleKeywords: ['医疗', '症状', '诊断', '医生'], productivity: 'neutral' },
  { subtag: 'notes', parentTag: 'docs', domains: ['notion.so', 'obsidian.md', 'logseq.com', 'roamresearch.com', 'evernote.com', 'craft.do', 'bear.app'], pathKeywords: ['note', 'page', 'block', 'journal'], titleKeywords: ['笔记', '笔记', '知识库', 'notion'], productivity: 'productive' },
  { subtag: 'projectManagement', parentTag: 'docs', domains: ['jira.atlassian.net', 'trello.com', 'asana.com', 'clickup.com', 'linear.app', 'shortcut.com'], pathKeywords: ['board', 'sprint', 'task', 'issue', 'project'], titleKeywords: ['项目管理', '看板', '任务', 'sprint'], productivity: 'productive' },
  { subtag: 'email', parentTag: 'social', domains: ['mail.google.com', 'outlook.com', 'outlook.live.com', 'mail.qq.com', 'mail.163.com', 'proton.me', 'mail.yahoo.com'], pathKeywords: ['mail', 'inbox', 'compose', 'draft', 'sent'], titleKeywords: ['邮件', 'email', '收件箱'], productivity: 'productive' },
  { subtag: 'meeting', parentTag: 'social', domains: ['zoom.us', 'teams.microsoft.com', 'meet.google.com', 'webex.com'], pathKeywords: ['meeting', 'conference', 'call', 'video-call'], titleKeywords: ['会议', '视频会议', 'meeting'], productivity: 'productive' },
  { subtag: 'chat', parentTag: 'ai', domains: ['chat.openai.com', 'chatgpt.com', 'claude.ai', 'gemini.google.com', 'poe.com', 'character.ai', 'copilot.microsoft.com', 'chat.zhipu.ai', 'kimi.moonshot.cn', 'doubao.com', 'tongyi.aliyun.com', 'yiyan.baidu.com'], pathKeywords: ['chat', 'conversation', 'prompt', 'completions'], titleKeywords: ['对话', 'chat', 'gpt', '大模型', 'ai助手'], productivity: 'productive' },
  { subtag: 'imageGeneration', parentTag: 'ai', domains: ['midjourney.com', 'stability.ai', 'leonardo.ai', 'playground.ai', 'civitai.com', 'comfyui.com'], pathKeywords: ['generate', 'image', 'create', 'art'], titleKeywords: ['文生图', 'ai绘画', '图像生成', 'diffusion'], productivity: 'productive' },
  { subtag: 'codeAssistant', parentTag: 'ai', domains: ['cursor.com', 'github.com/features/copilot', 'windsurf.ai', 'augmentcode.com', 'v0.dev', 'bolt.new', 'lovable.dev'], pathKeywords: ['code', 'suggest', 'complete', 'generate'], titleKeywords: ['代码助手', 'ai编程', 'copilot', '代码生成'], productivity: 'productive' },
]

export const URL_SEMANTIC_PATTERNS: { pattern: string; tag: string; subtag?: string; confidence: number }[] = [
  { pattern: '/docs/', tag: 'tech', subtag: 'documentation', confidence: 0.6 },
  { pattern: '/documentation/', tag: 'tech', subtag: 'documentation', confidence: 0.6 },
  { pattern: '/api/', tag: 'tech', subtag: 'backend', confidence: 0.5 },
  { pattern: '/sdk/', tag: 'tech', confidence: 0.5 },
  { pattern: '/tutorial/', tag: 'education', subtag: 'selfLearning', confidence: 0.6 },
  { pattern: '/course/', tag: 'education', subtag: 'onlineCourse', confidence: 0.65 },
  { pattern: '/learn/', tag: 'education', subtag: 'selfLearning', confidence: 0.5 },
  { pattern: '/wiki/', tag: 'education', subtag: 'selfLearning', confidence: 0.55 },
  { pattern: '/blog/', tag: 'reading', subtag: 'articles', confidence: 0.5 },
  { pattern: '/post/', tag: 'reading', subtag: 'articles', confidence: 0.45 },
  { pattern: '/article/', tag: 'reading', subtag: 'articles', confidence: 0.5 },
  { pattern: '/questions/', tag: 'tech', subtag: 'opensource', confidence: 0.55 },
  { pattern: '/issues/', tag: 'tech', subtag: 'opensource', confidence: 0.5 },
  { pattern: '/watch', tag: 'video', subtag: 'longVideo', confidence: 0.5 },
  { pattern: '/video/', tag: 'video', subtag: 'longVideo', confidence: 0.55 },
  { pattern: '/live/', tag: 'video', subtag: 'liveStream', confidence: 0.55 },
  { pattern: '/shorts/', tag: 'video', subtag: 'shortVideo', confidence: 0.6 },
  { pattern: '/shop/', tag: 'shopping', subtag: 'ecommerce', confidence: 0.5 },
  { pattern: '/product/', tag: 'shopping', subtag: 'ecommerce', confidence: 0.45 },
  { pattern: '/recipe/', tag: 'food', subtag: 'recipes', confidence: 0.55 },
  { pattern: '/booking/', tag: 'travel', subtag: 'booking', confidence: 0.55 },
  { pattern: '/hotel/', tag: 'travel', subtag: 'booking', confidence: 0.55 },
  { pattern: '/flight/', tag: 'travel', subtag: 'booking', confidence: 0.55 },
  { pattern: '/search', tag: 'search', confidence: 0.4 },
  { pattern: '/mail/', tag: 'social', subtag: 'email', confidence: 0.5 },
  { pattern: '/inbox/', tag: 'social', subtag: 'email', confidence: 0.55 },
  { pattern: '/chat/', tag: 'ai', subtag: 'chat', confidence: 0.45 },
  { pattern: '/game/', tag: 'gaming', confidence: 0.5 },
  { pattern: '/news/', tag: 'news', confidence: 0.5 },
  { pattern: '/music/', tag: 'music', confidence: 0.5 },
  { pattern: '/health/', tag: 'health', confidence: 0.5 },
  { pattern: '/fitness/', tag: 'health', subtag: 'fitness', confidence: 0.55 },
  { pattern: '/design/', tag: 'design', confidence: 0.5 },
]

export const TAG_PRODUCTIVITY: Record<string, 'productive' | 'neutral' | 'unproductive'> = {
  tech: 'productive', education: 'productive', docs: 'productive', cloud: 'productive',
  design: 'productive', dev: 'productive', tools: 'productive', ai: 'productive',
  search: 'neutral', news: 'neutral', health: 'neutral', government: 'neutral',
  law: 'neutral', realestate: 'neutral', automotive: 'neutral', reading: 'neutral',
  finance: 'neutral', travel: 'neutral', food: 'neutral', jobs: 'neutral',
  sports: 'neutral', photography: 'neutral', forum: 'neutral', email: 'productive',
  social: 'unproductive', video: 'unproductive', gaming: 'unproductive',
  music: 'unproductive', shopping: 'unproductive', blog: 'neutral',
}
